# Generated by Django 2.2 on 2019-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191122_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Guitars'), ('B', 'Bass'), ('P', 'Piano')], max_length=2),
        ),
    ]
