# Generated by Django 2.2 on 2019-11-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191122_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Guitars'), ('BG', 'Bass Guitars'), ('K', 'Keyboards')], max_length=2),
        ),
    ]
