# Generated by Django 2.2 on 2019-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191122_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('G', 'Guitars'), ('BG', 'Bass Guitars')], max_length=2),
        ),
    ]
