# Generated by Django 2.2 on 2020-01-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bass',
        ),
    ]
