# Generated by Django 2.2 on 2020-01-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_guitar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guitar',
        ),
    ]
