# Generated by Django 2.2 on 2020-11-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_whishlist_whishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlistitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='whishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Whishlist',
        ),
        migrations.DeleteModel(
            name='WhishlistItem',
        ),
    ]
