# Generated by Django 2.2 on 2020-11-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
