# Generated by Django 2.2 on 2020-11-22 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_auto_20201122_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishist',
            new_name='Wishlist',
        ),
    ]
