# Generated by Django 2.2 on 2020-11-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_wishlist_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
