# Generated by Django 2.2 on 2020-11-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201126_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
