# Generated by Django 2.2 on 2020-11-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20201127_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
