# Generated by Django 2.2 on 2020-11-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemReview',
        ),
    ]
