# Generated by Django 2.2 on 2020-12-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Guitars', 'G'), ('Basses', 'B')], max_length=2),
        ),
    ]
