# Generated by Django 2.2 on 2020-12-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20201206_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
    ]
