# Generated by Django 2.2 on 2020-11-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_product', '0008_auto_20201129_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
