# Generated by Django 2.2 on 2020-12-19 18:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('review_product', '0009_auto_20201130_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
