# Generated by Django 2.2 on 2020-12-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_product', '0010_review_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
    ]
